/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Berk Gedik (https://sketchfab.com/berkgedik)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sci-fi-plant-capsule-bd2d05db1bf24143ac2030c57e1eb05e
Title: Sci-Fi Plant Capsule
*/

import React, { useRef,useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'


const Plant=(props) =>{
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/sci-fi_plant_capsule.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
    Object.values(actions).forEach(action => action.play());
  }, [actions]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Armature_12" scale={0.102}>
                <group name="Bone_2">
                  <group name="Bone001_1" position={[0, 3.157, 0]} rotation={[0, -0.031, 0]}>
                    <group
                      name="Plane016_0"
                      position={[0.016, 0.142, 0.018]}
                      rotation={[Math.PI, -1.162, Math.PI]}
                      scale={9.812}>
                      <mesh
                        name="Object_7"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_7.geometry}
                        material={materials['Capsule_01.001']}
                      />
                    </group>
                  </group>
                </group>
                <group name="Bone002_11" position={[0, -0.489, 0]}>
                  <group
                    name="Bone003_4"
                    position={[0.098, 2.04, 0.046]}
                    rotation={[1.021, -0.039, 0.419]}>
                    <group
                      name="Plane001_3"
                      position={[0.003, 0, -0.011]}
                      rotation={[1.218, -0.085, -2.957]}
                      scale={9.812}>
                      <mesh
                        name="Object_11"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_11.geometry}
                        material={materials.Leafs}
                      />
                    </group>
                  </group>
                  <group
                    name="Bone004_6"
                    position={[0.101, 2.648, 0.041]}
                    rotation={[-0.41, 0.129, -0.592]}>
                    <group name="Plane_5" rotation={[1.602, 0.044, 0.951]} scale={9.812}>
                      <mesh
                        name="Object_14"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_14.geometry}
                        material={materials.Leafs}
                      />
                    </group>
                  </group>
                  <group
                    name="Bone005_8"
                    position={[0.111, 2.383, 0.04]}
                    rotation={[-0.974, 0.332, 0.461]}>
                    <group name="Plane003_7" rotation={[1.623, 0.015, 0.28]} scale={9.812}>
                      <mesh
                        name="Object_17"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_17.geometry}
                        material={materials.Leafs}
                      />
                    </group>
                  </group>
                  <group
                    name="Bone006_10"
                    position={[0.045, 1.561, -0.147]}
                    rotation={[-0.832, 0.354, 0.181]}>
                    <group
                      name="Plane002_9"
                      position={[-0.001, 0.001, 0.006]}
                      rotation={[1.654, 0.038, 0.159]}
                      scale={9.812}>
                      <mesh
                        name="Object_20"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_20.geometry}
                        material={materials.Leafs}
                      />
                    </group>
                  </group>
                </group>
              </group>
              <group name="Cylinder003_13" position={[0, 0.251, 0]} rotation={[0, -Math.PI / 2, 0]}>
                <mesh
                  name="Object_22"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_22.geometry}
                  material={materials['Capsule_01.001']}
                />
              </group>
              <group name="Cylinder004_14" position={[0, 0.478, 0]} rotation={[0, -Math.PI / 2, 0]}>
                <mesh
                  name="Object_24"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_24.geometry}
                  material={materials['Capsule_01.001']}
                />
              </group>
              <group name="Cylinder005_15" position={[0, 0.478, 0]} rotation={[0, -Math.PI / 2, 0]}>
                <mesh
                  name="Object_26"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_26.geometry}
                  material={materials['Capsule_01.001']}
                />
              </group>
              <group
                name="Cylinder006_16"
                position={[-0.001, 0.478, 0]}
                rotation={[0, -Math.PI / 2, 0]}>
                <mesh
                  name="Object_28"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_28.geometry}
                  material={materials['Capsule_01.001']}
                />
              </group>
              <group
                name="Cylinder007_17"
                position={[0.134, 0.34, 0]}
                rotation={[0, -Math.PI / 2, 0]}>
                <mesh
                  name="Object_30"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_30.geometry}
                  material={materials['Capsule_01.001']}
                />
              </group>
              <group name="Cylinder008_18" position={[0, 0.251, 0]} rotation={[0, -Math.PI / 2, 0]}>
                <mesh
                  name="Object_32"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_32.geometry}
                  material={materials['Capsule_01.001']}
                />
              </group>
              <group
                name="Cylinder012_19"
                position={[-0.083, 0.381, 0.101]}
                rotation={[2.233, -0.643, 0.925]}>
                <mesh
                  name="Object_34"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_34.geometry}
                  material={materials['Capsule_01.001']}
                />
              </group>
              <group name="Cylinder013_20" position={[0, 0.478, 0]} rotation={[0, Math.PI / 2, 0]}>
                <mesh
                  name="Object_36"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_36.geometry}
                  material={materials['Capsule_01.001']}
                />
              </group>
              <group
                name="Cylinder014_21"
                position={[-0.135, 0.34, 0]}
                rotation={[0, Math.PI / 2, 0]}>
                <mesh
                  name="Object_38"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_38.geometry}
                  material={materials['Capsule_01.001']}
                />
              </group>
              <group name="Cylinder015_22" position={[0, 0.488, 0]} rotation={[0, Math.PI / 2, 0]}>
                <mesh
                  name="Object_40"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_40.geometry}
                  material={materials['Capsule_01.001']}
                />
              </group>
              <group name="Cylinder016_23" position={[0, 0.488, 0]} rotation={[0, Math.PI / 2, 0]}>
                <mesh
                  name="Object_42"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_42.geometry}
                  material={materials['Capsule_01.001']}
                />
              </group>
              <group
                name="Cylinder019_24"
                position={[-0.028, 0.478, 0]}
                rotation={[0, Math.PI / 2, 0]}>
                <mesh
                  name="Object_44"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_44.geometry}
                  material={materials['Capsule_01.001']}
                />
              </group>
              <group name="Cylinder020_25" position={[0, 0.45, 0]} rotation={[0, -Math.PI / 2, 0]}>
                <mesh
                  name="Object_46"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_46.geometry}
                  material={materials['Capsule_01.001']}
                />
              </group>
              <group name="Cylinder001_26" position={[0, 0.15, 0]} rotation={[0, -Math.PI / 2, 0]}>
                <mesh
                  name="Object_48"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_48.geometry}
                  material={materials['Capsule_02.001']}
                />
              </group>
              <group name="Cylinder009_27" position={[0, 0.147, 0]}>
                <mesh
                  name="Object_50"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_50.geometry}
                  material={materials['Capsule_02.001']}
                />
              </group>
              <group name="Cylinder002_28" position={[-0.064, 0.12, 0.102]} rotation={[0, 0.94, 0]}>
                <mesh
                  name="Object_52"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_52.geometry}
                  material={materials['Capsule_02.001']}
                />
              </group>
              <group name="Cube001_29" position={[-0.11, 0.042, 0.059]} rotation={[0, -1.079, 0]}>
                <mesh
                  name="Object_54"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_54.geometry}
                  material={materials['Capsule_02.001']}
                />
              </group>
              <group name="Cube002_30" position={[-0.097, 0.042, 0.078]} rotation={[0, -0.858, 0]}>
                <mesh
                  name="Object_56"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_56.geometry}
                  material={materials['Capsule_02.001']}
                />
              </group>
              <group
                name="BezierCurve_31"
                position={[-0.072, 0.297, 0.096]}
                rotation={[-Math.PI, 0.683, Math.PI / 2]}>
                <mesh
                  name="Object_58"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_58.geometry}
                  material={materials['Capsule_02.001']}
                />
              </group>
              <group
                name="BezierCurve001_32"
                position={[-0.076, 0.297, 0.092]}
                rotation={[-Math.PI, 0.683, Math.PI / 2]}>
                <mesh
                  name="Object_60"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_60.geometry}
                  material={materials['Capsule_02.001']}
                />
              </group>
              <group
                name="BezierCurve002_33"
                position={[-0.082, 0.297, 0.089]}
                rotation={[-Math.PI, 0.683, Math.PI / 2]}>
                <mesh
                  name="Object_62"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_62.geometry}
                  material={materials['Capsule_02.001']}
                />
              </group>
              <group
                name="Cylinder010_34"
                position={[-0.072, 0.233, 0.089]}
                rotation={[0.05, -0.094, 0.008]}>
                <mesh
                  name="Object_64"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_64.geometry}
                  material={materials['Capsule_02.001']}
                />
              </group>
              <group
                name="Cylinder011_35"
                position={[-0.085, 0.351, 0.103]}
                rotation={[-0.084, 0.007, -0.403]}>
                <mesh
                  name="Object_66"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_66.geometry}
                  material={materials['Capsule_02.001']}
                />
              </group>
              <group name="Cylinder017_36">
                <mesh
                  name="Object_68"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_68.geometry}
                  material={materials['Capsule_02.001']}
                />
              </group>
              <group name="Cylinder018_37" position={[0, -0.01, 0]} rotation={[0, -0.607, 0]}>
                <mesh
                  name="Object_70"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_70.geometry}
                  material={materials['Capsule_02.001']}
                />
              </group>
              <group name="Cylinder021_38" position={[-0.108, 0.056, 0.043]}>
                <mesh
                  name="Object_72"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_72.geometry}
                  material={materials['Capsule_02.001']}
                />
              </group>
              <group
                name="Ground001_39"
                position={[0, -0.06, 0]}
                rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                scale={1.006}>
                <mesh
                  name="Object_74"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_74.geometry}
                  material={materials['Ground.002']}
                />
              </group>
              <group name="Cylinder_40" position={[0, 0.151, 0]} rotation={[0, -Math.PI / 2, 0]}>
                <mesh
                  name="Object_76"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_76.geometry}
                  material={materials['Capsule_03.001']}
                />
              </group>
              <group
                name="Cube003_41"
                position={[0.004, -0.027, 0.005]}
                rotation={[-0.053, -Math.PI / 2, 0]}>
                <mesh
                  name="Object_78"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_78.geometry}
                  material={materials['Capsule_03.001']}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/sci-fi_plant_capsule.glb')


export default Plant;